version: '3'

services:
  # MySQL
  db:
    #platform: linux/x86_64
    image: mysql:latest
    container_name: rpa_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rpadb
      MYSQL_USER: rpa
      MYSQL_PASSWORD: rpa
      TZ: 'Asia/Tokyo'
    command: --default-authentication-plugin=mysql_native_password
    volumes:
    - ./mysql/data:/var/lib/mysql
    - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    - ./mysql/db/:/docker-entrypoint-initdb.d
    ports:
    - 3306:3306
