-- MySQL Script generated by MySQL Workbench
-- Mon Mar 27 21:11:44 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema rpadb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema rpadb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `rpadb` DEFAULT CHARACTER SET utf8 ;
USE `rpadb` ;

-- -----------------------------------------------------
-- Table `rpadb`.`DriversLicenses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rpadb`.`DriversLicenses` (
  `drivers_license_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` VARCHAR(45) NOT NULL,
  `full_name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NULL,
  `birthday` VARCHAR(45) NULL,
  `expiration_date` VARCHAR(45) NULL,
  `note` VARCHAR(120) NULL,
  PRIMARY KEY (`drivers_license_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rpadb`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rpadb`.`Users` (
  `line_id` INT NOT NULL,
  `name` VARCHAR(64) NULL,
  `user_id` VARCHAR(64) NULL,
  PRIMARY KEY (`line_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
